
/*------------------------------------------------------------------------------*/
/* 
			 
<auto-generated>
	This code was generated by a tool. 
	plc2c 2023.1.0.0 03/25/2025 05:35:52
			
	Changes to this file may cause incorrect behavior and will be lost if
	the code is regenerated. 
</auto-generated>
 
*/
/*------------------------------------------------------------------------------*/

#ifndef _FILE__PLCPRECOMP_H
#define _FILE__PLCPRECOMP_H 

#include "__stdlib_plc_type.h"

typedef struct p1Plc_fb_data_SR 
{
    PLC_DINT _type; 
    PLC_BOOL S1; 
    PLC_BOOL R; 
    PLC_BOOL Q1; 
} p1Plc_fb_data_SR;

typedef struct p1Plc_fb_data_RS 
{
    PLC_DINT _type; 
    PLC_BOOL S; 
    PLC_BOOL R1; 
    PLC_BOOL Q1; 
} p1Plc_fb_data_RS;

typedef struct p1Plc_fb_data_R_TRIG 
{
    PLC_DINT _type; 
    PLC_BOOL CLK; 
    PLC_BOOL Q; 
    PLC_BOOL M; 
} p1Plc_fb_data_R_TRIG;

typedef struct p1Plc_fb_data_F_TRIG 
{
    PLC_DINT _type; 
    PLC_BOOL CLK; 
    PLC_BOOL Q; 
    PLC_BOOL M; 
    PLC_BOOL FIRST_INVOKE; 
} p1Plc_fb_data_F_TRIG;

typedef struct p1Plc_fb_data_CTU 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL R; 
    PLC_INT PV; 
    PLC_BOOL Q; 
    PLC_INT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
} p1Plc_fb_data_CTU;

typedef struct p1Plc_fb_data_CTU_INT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL R; 
    PLC_INT PV; 
    PLC_BOOL Q; 
    PLC_INT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
} p1Plc_fb_data_CTU_INT;

typedef struct p1Plc_fb_data_CTU_DINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL R; 
    PLC_DINT PV; 
    PLC_BOOL Q; 
    PLC_DINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
} p1Plc_fb_data_CTU_DINT;

typedef struct p1Plc_fb_data_CTU_LINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL R; 
    PLC_LINT PV; 
    PLC_BOOL Q; 
    PLC_LINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
} p1Plc_fb_data_CTU_LINT;

typedef struct p1Plc_fb_data_CTU_UDINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL R; 
    PLC_UDINT PV; 
    PLC_BOOL Q; 
    PLC_UDINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
} p1Plc_fb_data_CTU_UDINT;

typedef struct p1Plc_fb_data_CTU_ULINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL R; 
    PLC_ULINT PV; 
    PLC_BOOL Q; 
    PLC_ULINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
} p1Plc_fb_data_CTU_ULINT;

typedef struct p1Plc_fb_data_CTD 
{
    PLC_DINT _type; 
    PLC_BOOL CD; 
    PLC_BOOL LD; 
    PLC_INT PV; 
    PLC_BOOL Q; 
    PLC_INT CV; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTD;

typedef struct p1Plc_fb_data_CTD_INT 
{
    PLC_DINT _type; 
    PLC_BOOL CD; 
    PLC_BOOL LD; 
    PLC_INT PV; 
    PLC_BOOL Q; 
    PLC_INT CV; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTD_INT;

typedef struct p1Plc_fb_data_CTD_DINT 
{
    PLC_DINT _type; 
    PLC_BOOL CD; 
    PLC_BOOL LD; 
    PLC_DINT PV; 
    PLC_BOOL Q; 
    PLC_DINT CV; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTD_DINT;

typedef struct p1Plc_fb_data_CTD_LINT 
{
    PLC_DINT _type; 
    PLC_BOOL CD; 
    PLC_BOOL LD; 
    PLC_LINT PV; 
    PLC_BOOL Q; 
    PLC_LINT CV; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTD_LINT;

typedef struct p1Plc_fb_data_CTD_UDINT 
{
    PLC_DINT _type; 
    PLC_BOOL CD; 
    PLC_BOOL LD; 
    PLC_UDINT PV; 
    PLC_BOOL Q; 
    PLC_UDINT CV; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTD_UDINT;

typedef struct p1Plc_fb_data_CTD_ULINT 
{
    PLC_DINT _type; 
    PLC_BOOL CD; 
    PLC_BOOL LD; 
    PLC_ULINT PV; 
    PLC_BOOL Q; 
    PLC_ULINT CV; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTD_ULINT;

typedef struct p1Plc_fb_data_CTUD 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL CD; 
    PLC_BOOL R; 
    PLC_BOOL LD; 
    PLC_INT PV; 
    PLC_BOOL QU; 
    PLC_BOOL QD; 
    PLC_INT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTUD;

typedef struct p1Plc_fb_data_CTUD_INT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL CD; 
    PLC_BOOL R; 
    PLC_BOOL LD; 
    PLC_INT PV; 
    PLC_BOOL QU; 
    PLC_BOOL QD; 
    PLC_INT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTUD_INT;

typedef struct p1Plc_fb_data_CTUD_DINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL CD; 
    PLC_BOOL R; 
    PLC_BOOL LD; 
    PLC_DINT PV; 
    PLC_BOOL QU; 
    PLC_BOOL QD; 
    PLC_DINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTUD_DINT;

typedef struct p1Plc_fb_data_CTUD_UDINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL CD; 
    PLC_BOOL R; 
    PLC_BOOL LD; 
    PLC_UDINT PV; 
    PLC_BOOL QU; 
    PLC_BOOL QD; 
    PLC_UDINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTUD_UDINT;

typedef struct p1Plc_fb_data_CTUD_LINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL CD; 
    PLC_BOOL R; 
    PLC_BOOL LD; 
    PLC_LINT PV; 
    PLC_BOOL QU; 
    PLC_BOOL QD; 
    PLC_LINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTUD_LINT;

typedef struct p1Plc_fb_data_CTUD_ULINT 
{
    PLC_DINT _type; 
    PLC_BOOL CU; 
    PLC_BOOL CD; 
    PLC_BOOL R; 
    PLC_BOOL LD; 
    PLC_ULINT PV; 
    PLC_BOOL QU; 
    PLC_BOOL QD; 
    PLC_ULINT CV; 
    p1Plc_fb_data_R_TRIG CU_TRIG; 
    p1Plc_fb_data_R_TRIG CD_TRIG; 
} p1Plc_fb_data_CTUD_ULINT;

typedef struct p1Plc_fb_data_TP 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_TIME PT; 
    PLC_BOOL Q; 
    PLC_TIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_TIME SAVENOW; 
    PLC_TIME SAVEPT; 
    PLC_TIME ELAPSEDTIME; 
} p1Plc_fb_data_TP;

typedef struct p1Plc_fb_data_TP_TIME 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_TIME PT; 
    PLC_BOOL Q; 
    PLC_TIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_TIME SAVENOW; 
    PLC_TIME SAVEPT; 
    PLC_TIME ELAPSEDTIME; 
} p1Plc_fb_data_TP_TIME;

typedef struct p1Plc_fb_data_TP_LTIME 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_LTIME PT; 
    PLC_BOOL Q; 
    PLC_LTIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_LTIME SAVENOW; 
    PLC_LTIME SAVEPT; 
    PLC_LTIME ELAPSEDTIME; 
} p1Plc_fb_data_TP_LTIME;

typedef struct p1Plc_fb_data_TON 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_TIME PT; 
    PLC_BOOL Q; 
    PLC_TIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_TIME SAVENOW; 
    PLC_TIME SAVEPT; 
    PLC_TIME ELAPSEDTIME; 
} p1Plc_fb_data_TON;

typedef struct p1Plc_fb_data_TON_TIME 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_TIME PT; 
    PLC_BOOL Q; 
    PLC_TIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_TIME SAVENOW; 
    PLC_TIME SAVEPT; 
    PLC_TIME ELAPSEDTIME; 
} p1Plc_fb_data_TON_TIME;

typedef struct p1Plc_fb_data_TON_LTIME 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_LTIME PT; 
    PLC_BOOL Q; 
    PLC_LTIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_LTIME SAVENOW; 
    PLC_LTIME SAVEPT; 
    PLC_LTIME ELAPSEDTIME; 
} p1Plc_fb_data_TON_LTIME;

typedef struct p1Plc_fb_data_TOF 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_TIME PT; 
    PLC_BOOL Q; 
    PLC_TIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_TIME SAVENOW; 
    PLC_TIME SAVEPT; 
    PLC_TIME ELAPSEDTIME; 
} p1Plc_fb_data_TOF;

typedef struct p1Plc_fb_data_TOF_TIME 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_TIME PT; 
    PLC_BOOL Q; 
    PLC_TIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_TIME SAVENOW; 
    PLC_TIME SAVEPT; 
    PLC_TIME ELAPSEDTIME; 
} p1Plc_fb_data_TOF_TIME;

typedef struct p1Plc_fb_data_TOF_LTIME 
{
    PLC_DINT _type; 
    PLC_BOOL IN; 
    PLC_LTIME PT; 
    PLC_BOOL Q; 
    PLC_LTIME ET; 
    PLC_BOOL SAVEIN; 
    PLC_LTIME SAVENOW; 
    PLC_LTIME SAVEPT; 
    PLC_LTIME ELAPSEDTIME; 
} p1Plc_fb_data_TOF_LTIME;

typedef struct p1Plc_fb_data_SFC_TIMER 
{
    PLC_DINT _type; 
    PLC_UDINT START_TIME; 
    PLC_TIME STORED_TIME; 
    PLC_BOOL IS_STARTED; 
} p1Plc_fb_data_SFC_TIMER;

typedef struct p1Plc_fb_data_SFC_STEP 
{
    PLC_DINT _type; 
    PLC_BOOL X; 
    PLC_TIME T; 
    PLC_BOOL ACTIVE; 
    PLC_BOOL NEW_X; 
    p1Plc_fb_data_SFC_TIMER TIMER; 
} p1Plc_fb_data_SFC_STEP;

typedef struct p1Plc_fb_data_SFC_INIT_STEP 
{
    PLC_DINT _type; 
    PLC_BOOL X; 
    PLC_TIME T; 
    PLC_BOOL ACTIVE; 
    PLC_BOOL NEW_X; 
    p1Plc_fb_data_SFC_TIMER TIMER; 
} p1Plc_fb_data_SFC_INIT_STEP;

typedef struct p1Plc_fb_data_SFC_ACTION 
{
    PLC_DINT _type; 
    PLC_BOOL Q; 
} p1Plc_fb_data_SFC_ACTION;

typedef struct p1Plc_fb_data_SFC_ACTION_CONTROL 
{
    PLC_DINT _type; 
    PLC_BOOL N; 
    PLC_BOOL R; 
    PLC_BOOL S; 
    PLC_BOOL L; 
    PLC_BOOL D; 
    PLC_BOOL P; 
    PLC_BOOL P1; 
    PLC_BOOL P0; 
    PLC_BOOL SD; 
    PLC_BOOL DS; 
    PLC_BOOL SL; 
    PLC_BOOL AC; 
    PLC_TIME T; 
    PLC_BOOL Q; 
    PLC_BOOL A; 
    p1Plc_fb_data_RS S_FF; 
    p1Plc_fb_data_TON L_TMR; 
    p1Plc_fb_data_TON D_TMR; 
    p1Plc_fb_data_R_TRIG P_TRIG; 
    p1Plc_fb_data_RS SD_FF; 
    p1Plc_fb_data_TON SD_TMR; 
    p1Plc_fb_data_TON DS_TMR; 
    p1Plc_fb_data_RS DS_FF; 
    p1Plc_fb_data_RS SL_FF; 
    p1Plc_fb_data_TON SL_TMR; 
    p1Plc_fb_data_F_TRIG Q_TRIG; 
    p1Plc_fb_data_R_TRIG P1_TRIG; 
    p1Plc_fb_data_F_TRIG P0_TRIG; 
} p1Plc_fb_data_SFC_ACTION_CONTROL;

typedef PLC_USINT p1Plc_ar_USINT_100[100];

typedef struct p1Plc_STRING_255 
{
    PLC_UINT cur_len; 
    PLC_CHAR value[255]; 
} p1Plc_STRING_255;

void __MAIN_INIT();

void p1Plc_func_BLACKOUTTXT(
    PLC_BOOL* local_ENO, 
    PLC_BOOL local_BLKOUTSET, 
    PLC_STRING_REF local_BLKOUTTEXT, 
    PLC_STRING_REF local_BLACKOUTTXT);

PLC_DINT p1Plc_func_FAULTBITTEXT(
    PLC_BOOL* local_ENO, 
    PLC_BOOL local_FAULT_STATUS_BOOL, 
    PLC_BOOL local_BIT_STATUS_BOOL, 
    PLC_STRING_REF local_FAULT_STATUS_STRING, 
    PLC_STRING_REF local_BIT_STATUS_STRING);

PLC_DINT p1Plc_func_ORGANIZE_INTS(
    PLC_BOOL* local_ENO, 
    PLC_USINT local_FFD1_0, 
    PLC_BOOL local_FFD1_0_UPDATE, 
    PLC_USINT local_FFD1_1, 
    PLC_BOOL local_FFD1_1_UPDATE, 
    PLC_USINT local_FFD1_2, 
    PLC_BOOL local_FFD1_2_UPDATE, 
    PLC_USINT local_FFD1_3, 
    PLC_BOOL local_FFD1_3_UPDATE, 
    PLC_USINT local_FFD1_4, 
    PLC_BOOL local_FFD1_4_UPDATE, 
    PLC_USINT local_FFD1_5, 
    PLC_BOOL local_FFD1_5_UPDATE, 
    PLC_USINT local_FFD1_6, 
    PLC_BOOL local_FFD1_6_UPDATE, 
    PLC_USINT local_FFD1_7, 
    PLC_BOOL local_FFD1_7_UPDATE, 
    PLC_USINT local_FFD1_8, 
    PLC_BOOL local_FFD1_8_UPDATE, 
    PLC_USINT local_FFD1_9, 
    PLC_BOOL local_FFD1_9_UPDATE, 
    PLC_USINT local_FFD1_10, 
    PLC_BOOL local_FFD1_10_UPDATE, 
    PLC_USINT local_FFD1_11, 
    PLC_BOOL local_FFD1_11_UPDATE, 
    PLC_USINT local_FFD2_0, 
    PLC_BOOL local_FFD2_0_UPDATE, 
    PLC_USINT local_FFD2_1, 
    PLC_BOOL local_FFD2_1_UPDATE, 
    PLC_USINT local_FFD2_2, 
    PLC_BOOL local_FFD2_2_UPDATE, 
    PLC_USINT local_FFD2_3, 
    PLC_BOOL local_FFD2_3_UPDATE, 
    PLC_USINT local_FFD2_4, 
    PLC_BOOL local_FFD2_4_UPDATE, 
    PLC_USINT local_FFD2_5, 
    PLC_BOOL local_FFD2_5_UPDATE, 
    PLC_USINT local_FFD2_6, 
    PLC_BOOL local_FFD2_6_UPDATE, 
    PLC_USINT local_FFD2_7, 
    PLC_BOOL local_FFD2_7_UPDATE, 
    PLC_USINT local_FFD2_8, 
    PLC_BOOL local_FFD2_8_UPDATE, 
    PLC_USINT local_FFD2_9, 
    PLC_BOOL local_FFD2_9_UPDATE, 
    PLC_USINT local_FFD2_10, 
    PLC_BOOL local_FFD2_10_UPDATE, 
    PLC_USINT local_FFD2_11, 
    PLC_BOOL local_FFD2_11_UPDATE, 
    PLC_USINT local_FFD2_12, 
    PLC_BOOL local_FFD2_12_UPDATE, 
    PLC_USINT local_FFD2_13, 
    PLC_BOOL local_FFD2_13_UPDATE, 
    PLC_USINT local_FFD2_14, 
    PLC_BOOL local_FFD2_14_UPDATE, 
    PLC_USINT local_FFD2_15, 
    PLC_BOOL local_FFD2_15_UPDATE, 
    PLC_USINT local_FFD2_16, 
    PLC_BOOL local_FFD2_16_UPDATE, 
    PLC_USINT local_FFD2_17, 
    PLC_BOOL local_FFD2_17_UPDATE, 
    PLC_USINT local_FFD2_18, 
    PLC_BOOL local_FFD2_18_UPDATE, 
    PLC_USINT local_FFD2_19, 
    PLC_BOOL local_FFD2_19_UPDATE, 
    PLC_USINT local_FFD2_20, 
    PLC_BOOL local_FFD2_20_UPDATE, 
    PLC_USINT local_FFD2_21, 
    PLC_BOOL local_FFD2_21_UPDATE, 
    PLC_USINT local_FFD2_22, 
    PLC_BOOL local_FFD2_22_UPDATE, 
    PLC_USINT local_FFD2_23, 
    PLC_BOOL local_FFD2_23_UPDATE, 
    PLC_USINT local_FFD3_0, 
    PLC_USINT local_FFD3_1, 
    PLC_USINT local_FFD3_2, 
    PLC_USINT local_FFD3_3, 
    PLC_USINT local_FFD3_4, 
    PLC_USINT local_FFD3_5, 
    PLC_USINT local_FFD3_6, 
    PLC_USINT local_FFD3_7, 
    PLC_USINT local_FFD3_8, 
    PLC_USINT local_FFD3_9, 
    PLC_USINT local_FFD3_10, 
    PLC_USINT local_FFD3_11, 
    PLC_USINT local_FFD3_12, 
    PLC_USINT local_FFD3_13, 
    PLC_USINT local_FFD3_14, 
    PLC_USINT local_FFD3_15, 
    PLC_USINT local_FFD3_16, 
    PLC_USINT local_FFD3_17, 
    PLC_USINT local_FFD3_18, 
    PLC_USINT local_FFD3_19, 
    PLC_USINT local_FFD3_20, 
    PLC_USINT local_FFD3_21, 
    PLC_USINT local_FFD3_22, 
    PLC_USINT local_FFD3_23, 
    PLC_USINT local_FFD3_24, 
    PLC_USINT local_FFD3_25, 
    PLC_USINT local_FFD3_26, 
    PLC_USINT local_FFD3_27, 
    PLC_USINT local_FFD3_28, 
    PLC_USINT local_FFD3_29, 
    PLC_USINT local_FFD3_30, 
    PLC_BOOL local_BIT_STATUS_UPDATE, 
    PLC_BOOL local_INIT_NV_LOG, 
    PLC_USINT* local_ORG_INTS, 
    PLC_USINT* local_NUMBER_OF_INTS, 
    PLC_BOOL* local_UPDATE_MEMORY);

PLC_INT p1Plc_func_MEM_SORT(
    PLC_BOOL* local_ENO, 
    PLC_BOOL local_NOMEMSTORE, 
    PLC_BOOL local_FIRSTRUNDONE, 
    PLC_USINT local_LOG_VAL_0, 
    PLC_USINT local_LOG_VAL_1, 
    PLC_USINT local_LOG_VAL_2, 
    PLC_USINT local_LOG_VAL_3, 
    PLC_USINT local_LOG_VAL_4, 
    PLC_USINT local_LOG_VAL_5, 
    PLC_USINT local_LOG_VAL_6, 
    PLC_USINT local_LOG_VAL_7, 
    PLC_USINT local_LOG_VAL_8, 
    PLC_USINT local_LOG_VAL_9, 
    PLC_USINT local_LOG_VAL_10, 
    PLC_USINT local_LOG_VAL_11, 
    PLC_USINT local_LOG_VAL_12, 
    PLC_USINT local_LOG_VAL_13, 
    PLC_USINT local_LOG_VAL_14, 
    PLC_USINT local_LOG_VAL_15, 
    PLC_USINT local_LOG_VAL_16, 
    PLC_USINT local_LOG_VAL_17, 
    PLC_USINT local_LOG_VAL_18, 
    PLC_USINT local_LOG_VAL_19, 
    PLC_USINT local_LOG_VAL_20, 
    PLC_USINT local_LOG_VAL_21, 
    PLC_USINT local_LOG_VAL_22, 
    PLC_USINT local_LOG_VAL_23, 
    PLC_USINT local_LOG_VAL_24, 
    PLC_USINT local_LOG_VAL_25, 
    PLC_USINT local_LOG_VAL_26, 
    PLC_USINT local_LOG_VAL_27, 
    PLC_USINT local_LOG_VAL_28, 
    PLC_USINT local_LOG_VAL_29, 
    PLC_USINT local_LOG_VAL_30, 
    PLC_USINT local_LOG_VAL_31, 
    PLC_USINT local_LOG_VAL_32, 
    PLC_USINT local_LOG_VAL_33, 
    PLC_USINT local_LOG_VAL_34, 
    PLC_USINT local_LOG_VAL_35, 
    PLC_USINT local_LOG_VAL_36, 
    PLC_USINT local_LOG_VAL_37, 
    PLC_USINT local_LOG_VAL_38, 
    PLC_USINT local_LOG_VAL_39, 
    PLC_USINT local_LOG_VAL_40, 
    PLC_USINT local_LOG_VAL_41, 
    PLC_USINT local_LOG_VAL_42, 
    PLC_USINT local_LOG_VAL_43, 
    PLC_USINT local_LOG_VAL_44, 
    PLC_USINT local_LOG_VAL_45, 
    PLC_USINT local_LOG_VAL_46, 
    PLC_USINT local_LOG_VAL_47, 
    PLC_USINT local_LOG_VAL_48, 
    PLC_USINT local_LOG_VAL_49, 
    PLC_USINT local_LOG_VAL_50, 
    PLC_USINT local_LOG_VAL_51, 
    PLC_USINT local_LOG_VAL_52, 
    PLC_USINT local_LOG_VAL_53, 
    PLC_USINT local_LOG_VAL_54, 
    PLC_USINT local_LOG_VAL_55, 
    PLC_USINT local_LOG_VAL_56, 
    PLC_USINT local_LOG_VAL_57, 
    PLC_USINT local_LOG_VAL_58, 
    PLC_USINT local_LOG_VAL_59, 
    PLC_USINT local_LOG_VAL_60, 
    PLC_USINT local_LOG_VAL_61, 
    PLC_USINT local_LOG_VAL_62, 
    PLC_USINT local_LOG_VAL_63, 
    PLC_USINT local_LOG_VAL_64, 
    PLC_USINT local_LOG_VAL_65, 
    PLC_USINT local_LOG_VAL_66, 
    PLC_USINT local_LOG_VAL_67, 
    PLC_USINT local_LOG_VAL_68, 
    PLC_USINT local_LOG_VAL_69, 
    PLC_USINT local_LOG_VAL_70, 
    PLC_USINT local_LOG_VAL_71, 
    PLC_USINT local_LOG_VAL_72, 
    PLC_USINT local_LOG_VAL_73, 
    PLC_USINT local_LOG_VAL_74, 
    PLC_USINT local_LOG_VAL_75, 
    PLC_USINT local_LOG_VAL_76, 
    PLC_USINT local_LOG_VAL_77, 
    PLC_USINT local_LOG_VAL_78, 
    PLC_USINT local_LOG_VAL_79, 
    PLC_USINT local_LOG_VAL_80, 
    PLC_USINT local_LOG_VAL_81, 
    PLC_USINT local_LOG_VAL_82, 
    PLC_USINT local_LOG_VAL_83, 
    PLC_USINT local_LOG_VAL_84, 
    PLC_USINT local_LOG_VAL_85, 
    PLC_USINT local_LOG_VAL_86, 
    PLC_USINT local_LOG_VAL_87, 
    PLC_USINT local_LOG_VAL_88, 
    PLC_USINT local_LOG_VAL_89, 
    PLC_USINT local_LOG_VAL_90, 
    PLC_USINT local_LOG_VAL_91, 
    PLC_USINT local_LOG_VAL_92, 
    PLC_USINT local_LOG_VAL_93, 
    PLC_USINT local_LOG_VAL_94, 
    PLC_USINT local_LOG_VAL_95, 
    PLC_USINT local_LOG_VAL_96, 
    PLC_USINT local_LOG_VAL_97, 
    PLC_USINT local_LOG_VAL_98, 
    PLC_USINT local_LOG_VAL_99, 
    PLC_USINT local_LIST_HEAD, 
    PLC_USINT local_LIST_LENGTH, 
    PLC_USINT local_NUMBER_OF_INTS, 
    PLC_USINT* local_ORG_INTS, 
    PLC_USINT* local_CUR_LOG, 
    PLC_BOOL local_RES_LIST, 
    PLC_BOOL* local_FIRSTRUNDONEOUT, 
    PLC_USINT* local_LOG_HEAD, 
    PLC_USINT* local_LOG_COUNT, 
    PLC_USINT* local_LOG_ARRAY, 
    PLC_USINT* local_MEMSLOTOUT_1, 
    PLC_USINT* local_MEMSLOTOUT_2, 
    PLC_USINT* local_MEMSLOTOUT_3, 
    PLC_USINT* local_MEMSLOTOUT_4, 
    PLC_USINT* local_MEMSLOTOUT_5, 
    PLC_USINT* local_MEMSLOTOUT_6, 
    PLC_USINT* local_MEMSLOTOUT_7, 
    PLC_USINT* local_MEMSLOTOUT_8, 
    PLC_USINT* local_MEMSLOTOUT_9, 
    PLC_USINT* local_MEMSLOTOUT_10, 
    PLC_USINT* local_MEMSLOTOUT_11, 
    PLC_USINT* local_MEMSLOTOUT_12, 
    PLC_USINT* local_MEMSLOTOUT_13, 
    PLC_USINT* local_MEMSLOTOUT_14, 
    PLC_USINT* local_MEMSLOTOUT_15, 
    PLC_USINT* local_MEMSLOTOUT_16, 
    PLC_USINT* local_MEMSLOTOUT_17, 
    PLC_USINT* local_MEMSLOTOUT_18, 
    PLC_USINT* local_MEMSLOTOUT_19, 
    PLC_USINT* local_MEMSLOTOUT_20, 
    PLC_USINT* local_MEMSLOTOUT_21, 
    PLC_USINT* local_MEMSLOTOUT_22, 
    PLC_USINT* local_MEMSLOTOUT_23, 
    PLC_USINT* local_MEMSLOTOUT_24, 
    PLC_USINT* local_MEMSLOTOUT_25, 
    PLC_USINT* local_MEMSLOTOUT_26, 
    PLC_USINT* local_MEMSLOTOUT_27, 
    PLC_USINT* local_MEMSLOTOUT_28, 
    PLC_USINT* local_MEMSLOTOUT_29, 
    PLC_USINT* local_MEMSLOTOUT_30, 
    PLC_USINT* local_MEMSLOTOUT_31, 
    PLC_USINT* local_MEMSLOTOUT_32, 
    PLC_USINT* local_MEMSLOTOUT_33, 
    PLC_USINT* local_MEMSLOTOUT_34, 
    PLC_USINT* local_MEMSLOTOUT_35, 
    PLC_USINT* local_MEMSLOTOUT_36, 
    PLC_USINT* local_MEMSLOTOUT_37, 
    PLC_USINT* local_MEMSLOTOUT_38, 
    PLC_USINT* local_MEMSLOTOUT_39, 
    PLC_USINT* local_MEMSLOTOUT_40, 
    PLC_USINT* local_MEMSLOTOUT_41, 
    PLC_USINT* local_MEMSLOTOUT_42, 
    PLC_USINT* local_MEMSLOTOUT_43, 
    PLC_USINT* local_MEMSLOTOUT_44, 
    PLC_USINT* local_MEMSLOTOUT_45, 
    PLC_USINT* local_MEMSLOTOUT_46, 
    PLC_USINT* local_MEMSLOTOUT_47, 
    PLC_USINT* local_MEMSLOTOUT_48, 
    PLC_USINT* local_MEMSLOTOUT_49, 
    PLC_USINT* local_MEMSLOTOUT_50, 
    PLC_USINT* local_MEMSLOTOUT_51, 
    PLC_USINT* local_MEMSLOTOUT_52, 
    PLC_USINT* local_MEMSLOTOUT_53, 
    PLC_USINT* local_MEMSLOTOUT_54, 
    PLC_USINT* local_MEMSLOTOUT_55, 
    PLC_USINT* local_MEMSLOTOUT_56, 
    PLC_USINT* local_MEMSLOTOUT_57, 
    PLC_USINT* local_MEMSLOTOUT_58, 
    PLC_USINT* local_MEMSLOTOUT_59, 
    PLC_USINT* local_MEMSLOTOUT_60, 
    PLC_USINT* local_MEMSLOTOUT_61, 
    PLC_USINT* local_MEMSLOTOUT_62, 
    PLC_USINT* local_MEMSLOTOUT_63, 
    PLC_USINT* local_MEMSLOTOUT_64, 
    PLC_USINT* local_MEMSLOTOUT_65, 
    PLC_USINT* local_MEMSLOTOUT_66, 
    PLC_USINT* local_MEMSLOTOUT_67, 
    PLC_USINT* local_MEMSLOTOUT_68, 
    PLC_USINT* local_MEMSLOTOUT_69, 
    PLC_USINT* local_MEMSLOTOUT_70, 
    PLC_USINT* local_MEMSLOTOUT_71, 
    PLC_USINT* local_MEMSLOTOUT_72, 
    PLC_USINT* local_MEMSLOTOUT_73, 
    PLC_USINT* local_MEMSLOTOUT_74, 
    PLC_USINT* local_MEMSLOTOUT_75, 
    PLC_USINT* local_MEMSLOTOUT_76, 
    PLC_USINT* local_MEMSLOTOUT_77, 
    PLC_USINT* local_MEMSLOTOUT_78, 
    PLC_USINT* local_MEMSLOTOUT_79, 
    PLC_USINT* local_MEMSLOTOUT_80, 
    PLC_USINT* local_MEMSLOTOUT_81, 
    PLC_USINT* local_MEMSLOTOUT_82, 
    PLC_USINT* local_MEMSLOTOUT_83, 
    PLC_USINT* local_MEMSLOTOUT_84, 
    PLC_USINT* local_MEMSLOTOUT_85, 
    PLC_USINT* local_MEMSLOTOUT_86, 
    PLC_USINT* local_MEMSLOTOUT_87, 
    PLC_USINT* local_MEMSLOTOUT_88, 
    PLC_USINT* local_MEMSLOTOUT_89, 
    PLC_USINT* local_MEMSLOTOUT_90, 
    PLC_USINT* local_MEMSLOTOUT_91, 
    PLC_USINT* local_MEMSLOTOUT_92, 
    PLC_USINT* local_MEMSLOTOUT_93, 
    PLC_USINT* local_MEMSLOTOUT_94, 
    PLC_USINT* local_MEMSLOTOUT_95, 
    PLC_USINT* local_MEMSLOTOUT_96, 
    PLC_USINT* local_MEMSLOTOUT_97, 
    PLC_USINT* local_MEMSLOTOUT_98, 
    PLC_USINT* local_MEMSLOTOUT_99, 
    PLC_USINT* local_MEMSLOTOUT_100, 
    PLC_BOOL* local_LOG_VAL_1_UPDATE, 
    PLC_BOOL* local_LOG_VAL_2_UPDATE, 
    PLC_BOOL* local_LOG_VAL_3_UPDATE, 
    PLC_BOOL* local_LOG_VAL_4_UPDATE, 
    PLC_BOOL* local_LOG_VAL_5_UPDATE, 
    PLC_BOOL* local_LOG_VAL_6_UPDATE, 
    PLC_BOOL* local_LOG_VAL_7_UPDATE, 
    PLC_BOOL* local_LOG_VAL_8_UPDATE, 
    PLC_BOOL* local_LOG_VAL_9_UPDATE, 
    PLC_BOOL* local_LOG_VAL_10_UPDATE, 
    PLC_BOOL* local_LOG_VAL_11_UPDATE, 
    PLC_BOOL* local_LOG_VAL_12_UPDATE, 
    PLC_BOOL* local_LOG_VAL_13_UPDATE, 
    PLC_BOOL* local_LOG_VAL_14_UPDATE, 
    PLC_BOOL* local_LOG_VAL_15_UPDATE, 
    PLC_BOOL* local_LOG_VAL_16_UPDATE, 
    PLC_BOOL* local_LOG_VAL_17_UPDATE, 
    PLC_BOOL* local_LOG_VAL_18_UPDATE, 
    PLC_BOOL* local_LOG_VAL_19_UPDATE, 
    PLC_BOOL* local_LOG_VAL_20_UPDATE, 
    PLC_BOOL* local_LOG_VAL_21_UPDATE, 
    PLC_BOOL* local_LOG_VAL_22_UPDATE, 
    PLC_BOOL* local_LOG_VAL_23_UPDATE, 
    PLC_BOOL* local_LOG_VAL_24_UPDATE, 
    PLC_BOOL* local_LOG_VAL_25_UPDATE, 
    PLC_BOOL* local_LOG_VAL_INIT_UPDATE, 
    PLC_BOOL* local_UPDATE_LOG, 
    PLC_BOOL* local_UPDATE_LENGTH);

PLC_INT p1Plc_func_LOG_STRING(
    PLC_BOOL* local_ENO, 
    PLC_USINT local_LOG_HEAD, 
    PLC_USINT local_SCROLL_HEAD, 
    PLC_USINT* local_LOG_ARRAY, 
    PLC_BOOL local_LOG_TEST, 
    PLC_BOOL local_LOG_NOMEMSTORE, 
    PLC_USINT local_LIST_LENGTH, 
    PLC_STRING_REF local_LOG_OUTSTRING, 
    PLC_USINT* local_ADJUSTED_LOG, 
    PLC_BOOL* local_MADE_IT_HERE);

#endif /* _FILE__PLCPRECOMP_H */

