#ifndef __C49B02B97_88A0_4711_A8B6_DB8B71EA5BB0
#define __C49B02B97_88A0_4711_A8B6_DB8B71EA5BB0
#include "_TextDefinitions.h"
typedef struct {
//io data
       U8 Input_B_CAN_Input_B_ECU_Status_N_Battery_Enable_LED;
       PLC_STRING_REF Input_N_BlkOutText;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Fault_Status_LED;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Charge_Oload_Det_LED;
       U8 Input_B_CAN_Input_N_Batt_Curr_D_U8;
       U8 Input_B_CAN_Input_B_ECU_Status_N_SW_Oload_Det_LED;
       U8 Input_B_CAN_Input_B_ECU_Status_N_FET_Array_State_U8;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Battery_Mode_U8;
       BOOL Input_N_Indicator_Bool;
       U8 Input_B_CAN_Input_B_ECU_Status_N_TooCold_2Chrg_LED;
       S16 Input_B_CAN_Input_N_ECU_Temp_S16;
       S16 Input_B_CAN_Input_N_Cell_Temp1_S16;
       U8 Input_B_CAN_Input_N_Batt_Volt_W_U8;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Reserve_Prtct_Limit_Perc_D_U8;
       BOOL Input_N_Setting_PopUp;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Heater_Ctrl_LED;
       U8 Input_B_CAN_Input_B_ECU_Status_N_BIT_Status_LED;
       S16 Input_B_CAN_Input_N_Cell_Temp2_S16;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Oload_Latch_Status_LED;
       U8 Input_B_CAN_Input_N_Batt_Volt_D_U8;
       S32 Input_B_CAN_Input_N_Batt_Curr_W_S32;
       BOOL Input_N_IndicatorX_Bool;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Battle_Oride_Status_LED;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Reserve_Prtct_Warn_Reached_LED;
       U8 Input_B_CAN_Input_B_ECU_Status_N_SOC_Mode_U8;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Reserve_Prtct_Limit_Perc_W_U8;
       U8 Input_B_CAN_Input_B_ECU_Status_N_Reserve_Prtct_Enabled_LED;
       BOOL C49B02B97_88A0_4711_A8B6_DB8B71EA5BB0_Enable;
       S32 aXN352;
       BOOL aXN739;
       S32 aXN1802;
       BOOL aXN2201;
       S32 aXN2211;
 // lokala data
 BOOL _t_3_bOld1;
 union __SDTSampleData sample1_3_e[1];
 union __SDTSampleData sample2_3_f[1];
 struct __SdtSampleString StrSmplStruct_3_g;
 struct __SdtTextInstance textinst_3_d[2];
 BOOL _t_3_hOld1;
 union __SDTSampleData sample1_3_j[1];
 union __SDTSampleData sample2_3_k[1];
 struct __SdtSampleString StrSmplStruct_3_l;
 struct __SdtTextInstance textinst_3_i[2];
 BOOL _t_3_mOld1;
 union __SDTSampleData sample1_3_o[1];
 union __SDTSampleData sample2_3_p[1];
 struct __SdtSampleString StrSmplStruct_3_q;
 struct __SdtTextInstance textinst_3_n[2];
 BOOL _t_3_rOld1;
 union __SDTSampleData sample1_3_t[1];
 union __SDTSampleData sample2_3_u[1];
 struct __SdtSampleString StrSmplStruct_3_v;
 struct __SdtTextInstance textinst_3_s[2];
 BOOL _t_3_wOld1;
 BOOL _t_3_xOld1;
 BOOL _t_3_yOld1;
 BOOL _t_3_zOld1;
 BOOL _t_3_abOld1;
 BOOL _t_3_bbOld1;
 BOOL _t_3_cbOld1;
 BOOL _t_3_dbOld1;
 BOOL _t_3_ebOld1;
 BOOL _t_3_fbOld1;
 union __SDTSampleData sample1_3_hb[1];
 union __SDTSampleData sample2_3_ib[1];
 struct __SdtSampleString StrSmplStruct_3_jb;
 struct __SdtTextInstance textinst_3_gb[2];
 BOOL _t_3_kbOld1;
 union __SDTSampleData sample1_3_mb[1];
 union __SDTSampleData sample2_3_nb[1];
 struct __SdtSampleString StrSmplStruct_3_ob;
 struct __SdtTextInstance textinst_3_lb[2];
 BOOL _t_3_pbOld1;
 BOOL _t_3_qbOld1;
 union __SDTSampleData sample1_3_sb[1];
 union __SDTSampleData sample2_3_tb[1];
 struct __SdtSampleString StrSmplStruct_3_ub;
 struct __SdtTextInstance textinst_3_rb[2];
 BOOL _t_3_vbOld1;
 BOOL _t_3_wbOld1;
 union __SDTSampleData sample1_3_yb[1];
 union __SDTSampleData sample2_3_zb[1];
 struct __SdtSampleString StrSmplStruct_3_ac;
 struct __SdtTextInstance textinst_3_xb[2];
 BOOL _t_3_bcOld1;
 BOOL _t_3_ccOld1;
 union __SDTSampleData sample1_3_ec[1];
 union __SDTSampleData sample2_3_fc[1];
 struct __SdtSampleString StrSmplStruct_3_gc;
 struct __SdtTextInstance textinst_3_dc[2];
 BOOL _t_3_hcOld1;
 BOOL _t_3_icOld1;
 union __SDTSampleData sample1_3_kc[1];
 union __SDTSampleData sample2_3_lc[1];
 struct __SdtSampleString StrSmplStruct_3_mc;
 struct __SdtTextInstance textinst_3_jc[2];
 BOOL _t_3_ncOld1;
 BOOL _t_3_ocOld1;
 union __SDTSampleData sample1_3_qc[1];
 union __SDTSampleData sample2_3_rc[1];
 struct __SdtSampleString StrSmplStruct_3_sc;
 struct __SdtTextInstance textinst_3_pc[2];
 BOOL _t_3_tcOld1;
 BOOL _t_3_ucOld1;
 union __SDTSampleData sample1_3_wc[1];
 union __SDTSampleData sample2_3_xc[1];
 struct __SdtSampleString StrSmplStruct_3_yc;
 struct __SdtTextInstance textinst_3_vc[2];
 BOOL _t_3_zcOld1;
 BOOL _t_3_adOld1;
 union __SDTSampleData sample1_3_cd[1];
 union __SDTSampleData sample2_3_dd[1];
 struct __SdtSampleString StrSmplStruct_3_ed;
 struct __SdtTextInstance textinst_3_bd[2];
 BOOL _t_3_fdOld1;
 BOOL _t_3_gdOld1;
 union __SDTSampleData sample1_3_id[1];
 union __SDTSampleData sample2_3_jd[1];
 struct __SdtSampleString StrSmplStruct_3_kd;
 struct __SdtTextInstance textinst_3_hd[2];
 BOOL _t_3_ldOld1;
 BOOL _t_3_mdOld1;
 union __SDTSampleData sample1_3_od[1];
 union __SDTSampleData sample2_3_pd[1];
 struct __SdtSampleString StrSmplStruct_3_qd;
 struct __SdtTextInstance textinst_3_nd[2];
 BOOL _t_3_rdOld1;
 BOOL _t_3_sdOld1;
 union __SDTSampleData sample1_3_ud[1];
 union __SDTSampleData sample2_3_vd[1];
 struct __SdtSampleString StrSmplStruct_3_wd;
 struct __SdtTextInstance textinst_3_td[2];
 BOOL _t_3_xdOld1;
 BOOL _t_3_ydOld1;
 struct __SdtTextInstance TextlistArray_3_zd[8][2];
 union __SDTSampleData sample1_3_ae[1];
 union __SDTSampleData sample2_3_be[1];
 struct __SdtSampleString StrSmplStruct_3_ce;
 union __SDTSampleData sample1_3_de[1];
 union __SDTSampleData sample2_3_ee[1];
 struct __SdtSampleString StrSmplStruct_3_fe;
 union __SDTSampleData sample1_3_ge[1];
 union __SDTSampleData sample2_3_he[1];
 struct __SdtSampleString StrSmplStruct_3_ie;
 union __SDTSampleData sample1_3_je[1];
 union __SDTSampleData sample2_3_ke[1];
 struct __SdtSampleString StrSmplStruct_3_le;
 union __SDTSampleData sample1_3_me[1];
 union __SDTSampleData sample2_3_ne[1];
 struct __SdtSampleString StrSmplStruct_3_oe;
 union __SDTSampleData sample1_3_pe[1];
 union __SDTSampleData sample2_3_qe[1];
 struct __SdtSampleString StrSmplStruct_3_re;
 union __SDTSampleData sample1_3_se[1];
 union __SDTSampleData sample2_3_te[1];
 struct __SdtSampleString StrSmplStruct_3_ue;
 union __SDTSampleData sample1_3_ve[1];
 union __SDTSampleData sample2_3_we[1];
 struct __SdtSampleString StrSmplStruct_3_xe;
 BOOL _t_3_yeOld1;
 union __SDTSampleData sample1_3_af[1];
 union __SDTSampleData sample2_3_bf[1];
 struct __SdtSampleString StrSmplStruct_3_cf;
 struct __SdtTextInstance textinst_3_ze[2];
 BOOL _t_3_dfOld1;
 BOOL _t_3_efOld1;
 BOOL _t_3_ffOld1;
 BOOL _t_3_gfOld1;
 union __SDTSampleData sample1_3_if[1];
 union __SDTSampleData sample2_3_jf[1];
 struct __SdtSampleString StrSmplStruct_3_kf;
 struct __SdtTextInstance textinst_3_hf[2];
 BOOL _t_3_lfOld1;
 union __SDTSampleData sample1_3_nf[1];
 union __SDTSampleData sample2_3_of[1];
 struct __SdtSampleString StrSmplStruct_3_pf;
 struct __SdtTextInstance textinst_3_mf[2];
 BOOL _t_3_qfOld1;
 union __SDTSampleData sample1_3_sf[1];
 union __SDTSampleData sample2_3_tf[1];
 struct __SdtSampleString StrSmplStruct_3_uf;
 struct __SdtTextInstance textinst_3_rf[2];
 BOOL _t_3_vfOld1;
 union __SDTSampleData sample1_3_xf[2];
 union __SDTSampleData sample2_3_yf[2];
 struct __SdtTextInstance textinst_3_wf[2];
 BOOL _t_3_zfOld1;
 union __SDTSampleData sample1_3_bg[1];
 union __SDTSampleData sample2_3_cg[1];
 struct __SdtSampleString StrSmplStruct_3_dg;
 struct __SdtTextInstance textinst_3_ag[2];
 BOOL _t_3_egOld1;
 union __SDTSampleData sample1_3_gg[1];
 union __SDTSampleData sample2_3_hg[1];
 struct __SdtSampleString StrSmplStruct_3_ig;
 struct __SdtTextInstance textinst_3_fg[2];
 BOOL _t_3_jgOld1;
 union __SDTSampleData sample1_3_lg[2];
 union __SDTSampleData sample2_3_mg[2];
 struct __SdtTextInstance textinst_3_kg[2];
 BOOL _t_3_ngOld1;
 union __SDTSampleData sample1_3_pg[1];
 union __SDTSampleData sample2_3_qg[1];
 struct __SdtSampleString StrSmplStruct_3_rg;
 struct __SdtTextInstance textinst_3_og[2];
 BOOL _t_3_sgOld1;
 union __SDTSampleData sample1_3_ug[1];
 union __SDTSampleData sample2_3_vg[1];
 struct __SdtSampleString StrSmplStruct_3_wg;
 struct __SdtTextInstance textinst_3_tg[2];
 BOOL _t_3_xgOld1;
 union __SDTSampleData sample1_3_zg[2];
 union __SDTSampleData sample2_3_ah[2];
 struct __SdtTextInstance textinst_3_yg[2];
 BOOL _t_3_bhOld1;
 struct __SdtTextInstance TextlistArray_3_ch[8][2];
 union __SDTSampleData sample1_3_dh[1];
 union __SDTSampleData sample2_3_eh[1];
 struct __SdtSampleString StrSmplStruct_3_fh;
 union __SDTSampleData sample1_3_gh[1];
 union __SDTSampleData sample2_3_hh[1];
 struct __SdtSampleString StrSmplStruct_3_ih;
 union __SDTSampleData sample1_3_jh[1];
 union __SDTSampleData sample2_3_kh[1];
 struct __SdtSampleString StrSmplStruct_3_lh;
 union __SDTSampleData sample1_3_mh[1];
 union __SDTSampleData sample2_3_nh[1];
 struct __SdtSampleString StrSmplStruct_3_oh;
 union __SDTSampleData sample1_3_ph[1];
 union __SDTSampleData sample2_3_qh[1];
 struct __SdtSampleString StrSmplStruct_3_rh;
 union __SDTSampleData sample1_3_sh[1];
 union __SDTSampleData sample2_3_th[1];
 struct __SdtSampleString StrSmplStruct_3_uh;
 union __SDTSampleData sample1_3_vh[1];
 union __SDTSampleData sample2_3_wh[1];
 struct __SdtSampleString StrSmplStruct_3_xh;
 union __SDTSampleData sample1_3_yh[1];
 union __SDTSampleData sample2_3_zh[1];
 struct __SdtSampleString StrSmplStruct_3_ai;
 BOOL _t_3_biOld1;
 union __SDTSampleData sample1_3_di[1];
 union __SDTSampleData sample2_3_ei[1];
 struct __SdtSampleString StrSmplStruct_3_fi;
 struct __SdtTextInstance textinst_3_ci[2];
 BOOL _t_3_giOld1;
 struct __SdtTextInstance TextlistArray_3_hi[8][2];
 union __SDTSampleData sample1_3_ii[1];
 union __SDTSampleData sample2_3_ji[1];
 struct __SdtSampleString StrSmplStruct_3_ki;
 union __SDTSampleData sample1_3_li[1];
 union __SDTSampleData sample2_3_mi[1];
 struct __SdtSampleString StrSmplStruct_3_ni;
 union __SDTSampleData sample1_3_oi[1];
 union __SDTSampleData sample2_3_pi[1];
 struct __SdtSampleString StrSmplStruct_3_qi;
 union __SDTSampleData sample1_3_ri[1];
 union __SDTSampleData sample2_3_si[1];
 struct __SdtSampleString StrSmplStruct_3_ti;
 union __SDTSampleData sample1_3_ui[1];
 union __SDTSampleData sample2_3_vi[1];
 struct __SdtSampleString StrSmplStruct_3_wi;
 union __SDTSampleData sample1_3_xi[1];
 union __SDTSampleData sample2_3_yi[1];
 struct __SdtSampleString StrSmplStruct_3_zi;
 union __SDTSampleData sample1_3_aj[1];
 union __SDTSampleData sample2_3_bj[1];
 struct __SdtSampleString StrSmplStruct_3_cj;
 union __SDTSampleData sample1_3_dj[1];
 union __SDTSampleData sample2_3_ej[1];
 struct __SdtSampleString StrSmplStruct_3_fj;
 BOOL _t_3_gjOld1;
 union __SDTSampleData sample1_3_ij[1];
 union __SDTSampleData sample2_3_jj[1];
 struct __SdtSampleString StrSmplStruct_3_kj;
 struct __SdtTextInstance textinst_3_hj[2];
 BOOL _t_3_ljOld1;
 union __SDTSampleData sample1_3_nj[1];
 union __SDTSampleData sample2_3_oj[1];
 struct __SdtSampleString StrSmplStruct_3_pj;
 struct __SdtTextInstance textinst_3_mj[2];
 BOOL _t_3_qjOld1;
 union __SDTSampleData sample1_3_sj[1];
 union __SDTSampleData sample2_3_tj[1];
 struct __SdtSampleString StrSmplStruct_3_uj;
 struct __SdtTextInstance textinst_3_rj[2];
 BOOL _t_3_vjOld1;
 union __SDTSampleData sample1_3_xj[1];
 union __SDTSampleData sample2_3_yj[1];
 struct __SdtTextInstance textinst_3_wj[2];
 BOOL _t_3_zjOld1;
 union __SDTSampleData sample1_3_bk[1];
 union __SDTSampleData sample2_3_ck[1];
 struct __SdtSampleString StrSmplStruct_3_dk;
 struct __SdtTextInstance textinst_3_ak[2];
 BOOL _t_3_ekOld1;
 union __SDTSampleData sample1_3_gk[1];
 union __SDTSampleData sample2_3_hk[1];
 struct __SdtSampleString StrSmplStruct_3_ik;
 struct __SdtTextInstance textinst_3_fk[2];
 BOOL _t_3_jkOld1;
 union __SDTSampleData sample1_3_lk[1];
 union __SDTSampleData sample2_3_mk[1];
 struct __SdtTextInstance textinst_3_kk[2];
 BOOL _t_3_nkOld1;
 union __SDTSampleData sample1_3_pk[1];
 union __SDTSampleData sample2_3_qk[1];
 struct __SdtSampleString StrSmplStruct_3_rk;
 struct __SdtTextInstance textinst_3_ok[2];
 BOOL _t_3_skOld1;
 union __SDTSampleData sample1_3_uk[1];
 union __SDTSampleData sample2_3_vk[1];
 struct __SdtSampleString StrSmplStruct_3_wk;
 struct __SdtTextInstance textinst_3_tk[2];
 BOOL _t_3_xkOld1;
 union __SDTSampleData sample1_3_zk[1];
 union __SDTSampleData sample2_3_al[1];
 struct __SdtTextInstance textinst_3_yk[2];
 BOOL _t_3_blOld1;
 union __SDTSampleData sample1_3_dl[1];
 union __SDTSampleData sample2_3_el[1];
 struct __SdtSampleString StrSmplStruct_3_fl;
 struct __SdtTextInstance textinst_3_cl[2];
 BOOL _t_3_glOld1;
 BOOL _t_3_hlOld1;
 BOOL _t_3_ilOld1;
 BOOL _t_3_jlOld1;
 BOOL _t_3_klOld1;
 BOOL _t_3_llOld1;
 union __SDTSampleData sample1_3_nl[1];
 union __SDTSampleData sample2_3_ol[1];
 struct __SdtSampleString StrSmplStruct_3_pl;
 struct __SdtTextInstance textinst_3_ml[2];
 BOOL _t_3_qlOld1;
 BOOL _t_3_rlOld1;
 union __SDTSampleData sample1_3_tl[1];
 union __SDTSampleData sample2_3_ul[1];
 struct __SdtSampleString StrSmplStruct_3_vl;
 struct __SdtTextInstance textinst_3_sl[2];
 BOOL _t_3_wlOld1;
 union __SDTSampleData sample1_3_yl[2];
 union __SDTSampleData sample2_3_zl[2];
 struct __SdtSampleString StrSmplStruct_3_am;
 struct __SdtSampleString StrSmplStruct_3_bm;
 U8 StrBuf_3_cm[5000];
 U8 StrBuf_3_em[5000];
 struct __SdtSampleString StrSmplStruct_3_dm;
 struct __SdtTextInstance textinst_3_xl[2];
 BOOL _t_3_fmOld1;
} _C49B02B97_88A0_4711_A8B6_DB8B71EA5BB0_type;
void _C49B02B97_88A0_4711_A8B6_DB8B71EA5BB0(_C49B02B97_88A0_4711_A8B6_DB8B71EA5BB0_type *instanceStruct);
void _INITC49B02B97_88A0_4711_A8B6_DB8B71EA5BB0(_C49B02B97_88A0_4711_A8B6_DB8B71EA5BB0_type *instanceStruct);
#endif
